# Generated by Django 3.2.4 on 2021-06-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210628_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image2',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image5',
        ),
    ]
