# Generated by Django 3.2.4 on 2021-06-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210628_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='photo2',
        ),
        migrations.AddField(
            model_name='post',
            name='photo1',
            field=models.ImageField(default='defo', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo3',
            field=models.ImageField(blank=True, default='defo', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo4',
            field=models.ImageField(blank=True, default='defo', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo5',
            field=models.ImageField(blank=True, default='defo', null=True, upload_to='documents/'),
        ),
    ]
