# Generated by Django 3.2.4 on 2021-07-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210630_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='food_category',
            field=models.CharField(default='ramen', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='store_name',
            field=models.CharField(default='vantan', max_length=100),
            preserve_default=False,
        ),
    ]
