# Generated by Django 3.2.4 on 2021-07-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_photo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
